package com.prepa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T12:27:38.537-04:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://ws.breakdown.prepa.com", name = "BreakdownReportPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BreakdownReportPortType {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getBreakdownsSummaryResponse", targetNamespace = "http://ws.breakdown.prepa.com", partName = "parameters")
    @Action(input = "urn:getBreakdownsSummary", output = "urn:getBreakdownsSummaryResponse")
    @WebMethod(action = "urn:getBreakdownsSummary")
    public GetBreakdownsSummaryResponse getBreakdownsSummary();

    @WebResult(name = "return", targetNamespace = "http://ws.breakdown.prepa.com")
    @Action(input = "urn:getBreakdownsByTownOrCity", output = "urn:getBreakdownsByTownOrCityResponse")
    @RequestWrapper(localName = "getBreakdownsByTownOrCity", targetNamespace = "http://ws.breakdown.prepa.com", className = "com.prepa.GetBreakdownsByTownOrCity")
    @WebMethod(action = "urn:getBreakdownsByTownOrCity")
    @ResponseWrapper(localName = "getBreakdownsByTownOrCityResponse", targetNamespace = "http://ws.breakdown.prepa.com", className = "com.prepa.GetBreakdownsByTownOrCityResponse")
    public java.util.List<com.prepa.BreakdownArea> getBreakdownsByTownOrCity(
        @WebParam(name = "townOrCity", targetNamespace = "http://ws.breakdown.prepa.com")
        java.lang.String townOrCity
    );
}
